### ISSUE TITLE
关于zip包的一些问题和建议

### ISSUE THREAD

**Issue by winterszhangdong** [88250/gulu#5]
因为问题比较特殊，并且完全没有文档或者sample可以参考，所以请原谅没有用模板提issue。

请问zip这个模块经过测试了吗？我看你们test文件里并没有`AddEntryN`和`AddEntry`方法的测试。
比如`AddEntry`
https://github.com/88250/gulu/blob/07c3d1634ebf74a57f1c4ff956c373933670dbd2/zip.go#L61
这里的`path`和`name`分别应该指什么？

https://github.com/88250/gulu/blob/07c3d1634ebf74a57f1c4ff956c373933670dbd2/zip.go#L88
88行这里直接`Open(name)`，那name应该是要压缩的文件路径(包括路径名)？

https://github.com/88250/gulu/blob/07c3d1634ebf74a57f1c4ff956c373933670dbd2/zip.go#L72
但是，这里`path`应该就是要压缩的文件的路径(包括文件名)？如果这样的话，那name的意义是？

如果我的理解有误希望能指出，不过还是希望有个简单的文档或者几个sample能说明用法。

**Comment by 88250** [comment]
可参考 `AddDirectory`，里面用到了 `AddEntry`。
